### PR TITLE
Fix columns for wide screens

### LINKED ISSUE #30: Bug: two column layout broken
Originally the contract page was a two column layout (which I think makes sense on big screens). With the addition of the contract history, it broke.

**Expected**

Bildschirmfoto 2020-12-16 um 09 15 19

**Actual**

Bildschirmfoto 2020-12-16 um 09 16 38

@abefernan could you have a look at that? This problem exists on current master already and is probably indenpendent of your current work.

### PR DESCRIPTION
**Pull request by abefernan**
Closes #30

### CODE REVIEW

File: src/pages/contract/ContractPage.tsx [hunk 1]
```diff
@@ -134,7 +134,7 @@ export function ContractPage(): JSX.Element {
           </div>
         </div>
         <div className="row white-row">
-          <div className="col">
+          <div className="col-12 col-sm-12 col-md-6 col-xl-6">
```
Comment (webmaster128) [inline src/pages/contract/ContractPage.tsx:137]: Looking at https://getbootstrap.com/docs/4.1/layout/grid/#grid-options, it seems like we only need to set two classes: `col-12` for the smallest case and `col-md-6` for ≥768px.

Comment (webmaster128) [reply src/pages/contract/ContractPage.tsx:137]: Bootstrap 4.5 version of the docs is here: https://getbootstrap.com/docs/4.5/layout/grid/#grid-options

See also #32

Comment (webmaster128) [reply src/pages/contract/ContractPage.tsx:137]: The " <576px " for `.col-12` is misleading, since it is used for all screen sizes and then overridden. It should be documented as `≥ 0px`.

Bildschirmfoto 2020-12-16 um 13 35 20

**Review by webmaster128 — APPROVED** [review]
